version: '3.8'

services:
  llamafile:
    build:
      context: .
      dockerfile: Dockerfile.llamafile
    ports:
      - "8080:8080"
    volumes:
      - /home/user:/model  # Mount the home/user directory
    container_name: llamafile

  chatbot:
    build:
      context: ./chatbot
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - llamafile
    container_name: chatbot
    volumes:
      - /home/user:/model  # Ensure the chatbot has access to the model as well
