version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app  # Mount the app directory for live code updates
    environment:
      FLASK_ENV: development  # Set environment variables if needed
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
